name: Contributor Updater

on:
  push:
    paths: [ content/asciidoc-pages/** ]
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_contributors:
    if: github.repository_owner == 'adoptium'
    name: Check Contributors
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

    - id: files
      uses: jitterbit/get-changed-files@b17fbb00bdc0c0f63fcf166580804b4d2cdc2a42 # v1
      
    - run: pip3 install bs4

    - run: |
        # shellcheck disable=2043
        for changed_file in ${{ steps.files.outputs.all }}; do
          if [[ ${changed_file} =~ ^content/asciidoc.*.adoc ]]; then
            current_authors=$(grep ':page-authors:' "${changed_file}" | sed -n -e 's/^.*page-authors: //p')
            contibutors=$(python3 .github/workflows/github-file-contributors.py --file "${changed_file}")
            for contibutor in ${contibutors}; do
              if ! echo "${current_authors}" | grep "${contibutor}"; then
                echo "adding ${contibutor}"
                current_authors_replacement="${current_authors}, ${contibutor}"
                echo "${current_authors_replacement}"
                sed -i "s/${current_authors}/${current_authors_replacement}/g" "${changed_file}"
              fi
            done
          fi
        done

    - uses: gr2m/create-or-update-pull-request-action@dc1726cbf4dd3ce766af4ec29cfb660e0125e8ee # v1
      env:
        GITHUB_TOKEN: ${{ secrets.ADOPTIUM_TEMURIN_BOT_TOKEN }}
      with:
        title: "Update Asciidoc Contributors"
        body: "This is an automatically generated pull request, it will be automatically merged if all the CI tests pass."
        path: "content/asciidoc-pages/"
        branch: "contributor_bot"
        commit-message: "contributors: update asciidoc contributors"
        labels: automerge
        author: "eclipse-temurin-bot <temurin-bot@eclipse.org>"
